<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserLanguage extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'language_code', 
        'language_name'
    ];

    /**
     * Relationship with User model
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get all world languages with their codes
     * This function contains comprehensive list of world languages
     */
    public static function getWorldLanguages()
    {
        return [
            'aa' => 'Afar',
            'ab' => 'Abkhazian',
            'ace' => 'Acehnese',
            'ach' => 'Acoli',
            'ada' => 'Adangme',
            'ady' => 'Adyghe',
            'ae' => 'Avestan',
            'af' => 'Afrikaans',
            'ak' => 'Akan',
            'am' => 'Amharic',
            'an' => 'Aragonese',
            'ang' => 'Old English',
            'anp' => 'Angika',
            'ar' => 'Arabic',
            'arc' => 'Aramaic',
            'arn' => 'Mapuche',
            'aro' => 'Araona',
            'arp' => 'Arapaho',
            'arw' => 'Arawak',
            'as' => 'Assamese',
            'ast' => 'Asturian',
            'av' => 'Avaric',
            'awa' => 'Awadhi',
            'ay' => 'Aymara',
            'az' => 'Azerbaijani',
            'ba' => 'Bashkir',
            'bal' => 'Baluchi',
            'ban' => 'Balinese',
            'bar' => 'Bavarian',
            'bas' => 'Basa',
            'bcc' => 'Balochi',
            'bcl' => 'Bikol',
            'be' => 'Belarusian',
            'bej' => 'Beja',
            'bem' => 'Bemba',
            'ber' => 'Berber',
            'bg' => 'Bulgarian',
            'bh' => 'Bihari',
            'bho' => 'Bhojpuri',
            'bi' => 'Bislama',
            'bik' => 'Bikol',
            'bin' => 'Bini',
            'bjn' => 'Banjar',
            'bm' => 'Bambara',
            'bn' => 'Bengali',
            'bo' => 'Tibetan',
            'bpy' => 'Bishnupriya',
            'br' => 'Breton',
            'bra' => 'Braj',
            'brh' => 'Brahui',
            'brx' => 'Bodo',
            'bs' => 'Bosnian',
            'bss' => 'Akoose',
            'bua' => 'Buriat',
            'bug' => 'Buginese',
            'bxr' => 'Russia Buriat',
            'by' => 'Byelorussian',
            'ca' => 'Catalan',
            'cad' => 'Caddo',
            'car' => 'Carib',
            'cau' => 'Caucasian',
            'cch' => 'Atsam',
            'ce' => 'Chechen',
            'ceb' => 'Cebuano',
            'cel' => 'Celtic',
            'ch' => 'Chamorro',
            'chb' => 'Chibcha',
            'chg' => 'Chagatai',
            'chk' => 'Chuukese',
            'chm' => 'Mari',
            'chn' => 'Chinook jargon',
            'cho' => 'Choctaw',
            'chp' => 'Chipewyan',
            'chr' => 'Cherokee',
            'chy' => 'Cheyenne',
            'ckb' => 'Central Kurdish',
            'co' => 'Corsican',
            'cop' => 'Coptic',
            'cpe' => 'Creoles and pidgins',
            'cpf' => 'Creoles and pidgins',
            'cpp' => 'Creoles and pidgins',
            'cr' => 'Cree',
            'crh' => 'Crimean Tatar',
            'crp' => 'Creoles and pidgins',
            'cs' => 'Czech',
            'csb' => 'Kashubian',
            'cu' => 'Church Slavic',
            'cus' => 'Cushitic',
            'cv' => 'Chuvash',
            'cy' => 'Welsh',
            'da' => 'Danish',
            'dak' => 'Dakota',
            'dar' => 'Dargwa',
            'day' => 'Dayak',
            'de' => 'German',
            'del' => 'Delaware',
            'den' => 'Slave',
            'dgr' => 'Dogrib',
            'din' => 'Dinka',
            'doi' => 'Dogri',
            'dra' => 'Dravidian',
            'dsb' => 'Lower Sorbian',
            'dua' => 'Duala',
            'dum' => 'Dutch, Middle',
            'dv' => 'Divehi',
            'dyu' => 'Dyula',
            'dz' => 'Dzongkha',
            'ebu' => 'Embu',
            'ee' => 'Ewe',
            'efi' => 'Efik',
            'egy' => 'Egyptian',
            'eka' => 'Ekajuk',
            'el' => 'Greek',
            'elx' => 'Elamite',
            'en' => 'English',
            'enm' => 'English, Middle',
            'eo' => 'Esperanto',
            'es' => 'Spanish',
            'et' => 'Estonian',
            'eu' => 'Basque',
            'ewo' => 'Ewondo',
            'fa' => 'Persian',
            'fan' => 'Fang',
            'fat' => 'Fanti',
            'ff' => 'Fulah',
            'fi' => 'Finnish',
            'fil' => 'Filipino',
            'fiu' => 'Finno-Ugrian',
            'fj' => 'Fijian',
            'fo' => 'Faroese',
            'fon' => 'Fon',
            'fr' => 'French',
            'frm' => 'French, Middle',
            'fro' => 'French, Old',
            'frr' => 'Northern Frisian',
            'frs' => 'Eastern Frisian',
            'fur' => 'Friulian',
            'fy' => 'Western Frisian',
            'ga' => 'Irish',
            'gaa' => 'Ga',
            'gay' => 'Gayo',
            'gba' => 'Gbaya',
            'gd' => 'Gaelic',
            'gem' => 'Germanic',
            'gez' => 'Geez',
            'gil' => 'Gilbertese',
            'gl' => 'Galician',
            'gmh' => 'German, Middle High',
            'gn' => 'Guarani',
            'goh' => 'German, Old High',
            'gom' => 'Goan Konkani',
            'gon' => 'Gondi',
            'gor' => 'Gorontalo',
            'got' => 'Gothic',
            'grb' => 'Grebo',
            'grc' => 'Greek, Ancient',
            'gsw' => 'Swiss German',
            'gu' => 'Gujarati',
            'guc' => 'Wayuu',
            'gur' => 'Frafra',
            'guz' => 'Gusii',
            'gv' => 'Manx',
            'gwi' => 'Gwichin',
            'ha' => 'Hausa',
            'hai' => 'Haida',
            'hak' => 'Hakka Chinese',
            'haw' => 'Hawaiian',
            'he' => 'Hebrew',
            'hi' => 'Hindi',
            'hil' => 'Hiligaynon',
            'him' => 'Himachali',
            'hit' => 'Hittite',
            'hmn' => 'Hmong',
            'ho' => 'Hiri Motu',
            'hr' => 'Croatian',
            'hsb' => 'Upper Sorbian',
            'hsn' => 'Xiang Chinese',
            'ht' => 'Haitian',
            'hu' => 'Hungarian',
            'hup' => 'Hupa',
            'hy' => 'Armenian',
            'hz' => 'Herero',
            'ia' => 'Interlingua',
            'iba' => 'Iban',
            'ibb' => 'Ibibio',
            'id' => 'Indonesian',
            'ie' => 'Interlingue',
            'ig' => 'Igbo',
            'ii' => 'Sichuan Yi',
            'ijo' => 'Ijo',
            'ik' => 'Inupiaq',
            'ilo' => 'Iloko',
            'inc' => 'Indic',
            'ine' => 'Indo-European',
            'inh' => 'Ingush',
            'io' => 'Ido',
            'ira' => 'Iranian',
            'iro' => 'Iroquoian',
            'is' => 'Icelandic',
            'it' => 'Italian',
            'iu' => 'Inuktitut',
            'ja' => 'Japanese',
            'jbo' => 'Lojban',
            'jpr' => 'Judeo-Persian',
            'jrb' => 'Judeo-Arabic',
            'jv' => 'Javanese',
            'ka' => 'Georgian',
            'kaa' => 'Kara-Kalpak',
            'kab' => 'Kabyle',
            'kac' => 'Kachin',
            'kaj' => 'Jju',
            'kam' => 'Kamba',
            'kar' => 'Karen',
            'kaw' => 'Kawi',
            'kbd' => 'Kabardian',
            'kbl' => 'Kanembu',
            'kcg' => 'Tyap',
            'kde' => 'Makonde',
            'kea' => 'Kabuverdianu',
            'kfo' => 'Koro',
            'kg' => 'Kongo',
            'kha' => 'Khasi',
            'khi' => 'Khoisan',
            'kho' => 'Khotanese',
            'ki' => 'Kikuyu',
            'kj' => 'Kuanyama',
            'kk' => 'Kazakh',
            'kkj' => 'Kako',
            'kl' => 'Kalaallisut',
            'kln' => 'Kalenjin',
            'km' => 'Central Khmer',
            'kmb' => 'Kimbundu',
            'kn' => 'Kannada',
            'ko' => 'Korean',
            'kok' => 'Konkani',
            'kos' => 'Kosraean',
            'kpe' => 'Kpelle',
            'kr' => 'Kanuri',
            'krc' => 'Karachay-Balkar',
            'kri' => 'Krio',
            'krj' => 'Kinaray-a',
            'krl' => 'Karelian',
            'kro' => 'Kru',
            'kru' => 'Kurukh',
            'ks' => 'Kashmiri',
            'ksb' => 'Shambala',
            'ksh' => 'Colognian',
            'ku' => 'Kurdish',
            'kum' => 'Kumyk',
            'kut' => 'Kutenai',
            'kv' => 'Komi',
            'kw' => 'Cornish',
            'ky' => 'Kirghiz',
            'la' => 'Latin',
            'lad' => 'Ladino',
            'lag' => 'Langi',
            'lah' => 'Lahnda',
            'lam' => 'Lamba',
            'lb' => 'Luxembourgish',
            'lez' => 'Lezghian',
            'lg' => 'Ganda',
            'li' => 'Limburgan',
            'lij' => 'Ligurian',
            'lis' => 'Lisu',
            'lkt' => 'Lakota',
            'ln' => 'Lingala',
            'lo' => 'Lao',
            'lol' => 'Mongo',
            'loz' => 'Lozi',
            'lrc' => 'Northern Luri',
            'lt' => 'Lithuanian',
            'lu' => 'Luba-Katanga',
            'lua' => 'Luba-Lulua',
            'lui' => 'Luiseno',
            'lun' => 'Lunda',
            'luo' => 'Luo',
            'lus' => 'Mizo',
            'luy' => 'Luyia',
            'lv' => 'Latvian',
            'mad' => 'Madurese',
            'maf' => 'Mafa',
            'mag' => 'Magahi',
            'mai' => 'Maithili',
            'mak' => 'Makasar',
            'man' => 'Mandingo',
            'map' => 'Austronesian',
            'mas' => 'Masai',
            'mde' => 'Maba',
            'mdf' => 'Moksha',
            'mdr' => 'Mandar',
            'men' => 'Mende',
            'mer' => 'Meru',
            'mfe' => 'Morisyen',
            'mg' => 'Malagasy',
            'mga' => 'Irish, Middle',
            'mgh' => 'Makhuwa-Meetto',
            'mgo' => 'Meta',
            'mh' => 'Marshallese',
            'mi' => 'Maori',
            'mic' => 'Micmac',
            'min' => 'Minangkabau',
            'mis' => 'Uncoded languages',
            'mk' => 'Macedonian',
            'mkd' => 'Macedonian',
            'ml' => 'Malayalam',
            'mn' => 'Mongolian',
            'mnc' => 'Manchu',
            'mni' => 'Manipuri',
            'mns' => 'Mansi',
            'mo' => 'Moldavian',
            'moh' => 'Mohawk',
            'mos' => 'Mossi',
            'mr' => 'Marathi',
            'ms' => 'Malay',
            'mt' => 'Maltese',
            'mua' => 'Mundang',
            'mul' => 'Multiple languages',
            'mun' => 'Munda',
            'mus' => 'Creek',
            'mwl' => 'Mirandese',
            'mwr' => 'Marwari',
            'my' => 'Burmese',
            'myn' => 'Mayan',
            'myv' => 'Erzya',
            'na' => 'Nauru',
            'nah' => 'Nahuatl',
            'nai' => 'North American Indian',
            'nap' => 'Neapolitan',
            'naq' => 'Nama',
            'nb' => 'Norwegian Bokmål',
            'nd' => 'North Ndebele',
            'nds' => 'Low German',
            'ne' => 'Nepali',
            'new' => 'Nepal Bhasa',
            'ng' => 'Ndonga',
            'nia' => 'Nias',
            'nic' => 'Niger-Kordofanian',
            'niu' => 'Niuean',
            'nl' => 'Dutch',
            'nmg' => 'Kwasio',
            'nn' => 'Norwegian Nynorsk',
            'nnh' => 'Ngiemboon',
            'no' => 'Norwegian',
            'nog' => 'Nogai',
            'non' => 'Norse, Old',
            'nqo' => 'Nko',
            'nr' => 'South Ndebele',
            'nso' => 'Pedi',
            'nub' => 'Nubian',
            'nus' => 'Nuer',
            'nv' => 'Navajo',
            'nwc' => 'Classical Newari',
            'ny' => 'Chichewa',
            'nym' => 'Nyamwezi',
            'nyn' => 'Nyankole',
            'nyo' => 'Nyoro',
            'nzi' => 'Nzima',
            'oc' => 'Occitan',
            'oj' => 'Ojibwa',
            'om' => 'Oromo',
            'or' => 'Oriya',
            'os' => 'Ossetian',
            'osa' => 'Osage',
            'ota' => 'Turkish, Ottoman',
            'oto' => 'Otomian',
            'pa' => 'Panjabi',
            'paa' => 'Papuan',
            'pag' => 'Pangasinan',
            'pal' => 'Pahlavi',
            'pam' => 'Pampanga',
            'pap' => 'Papiamento',
            'pau' => 'Palauan',
            'pcc' => 'Bouyei',
            'pcd' => 'Picard',
            'pdc' => 'Pennsylvania German',
            'pdt' => 'Plautdietsch',
            'peo' => 'Persian, Old',
            'pfl' => 'Palatine German',
            'phn' => 'Phoenician',
            'pi' => 'Pali',
            'pl' => 'Polish',
            'pms' => 'Piemontese',
            'pnt' => 'Pontic',
            'pon' => 'Pohnpeian',
            'prg' => 'Prussian',
            'pro' => 'Provençal, Old',
            'ps' => 'Pushto',
            'pt' => 'Portuguese',
            'qu' => 'Quechua',
            'quc' => 'Kiche',
            'raj' => 'Rajasthani',
            'rap' => 'Rapanui',
            'rar' => 'Rarotongan',
            'rc' => 'Ruund',
            'rdf' => 'Rundi',
            'rgn' => 'Romagnol',
            'rif' => 'Riffian',
            'rm' => 'Romansh',
            'rn' => 'Kirundi',
            'ro' => 'Romanian',
            'roa' => 'Romance',
            'rof' => 'Rombo',
            'rom' => 'Romany',
            'root' => 'Root',
            'rtm' => 'Rotuman',
            'ru' => 'Russian',
            'rue' => 'Rusyn',
            'rug' => 'Roviana',
            'rup' => 'Aromanian',
            'rw' => 'Kinyarwanda',
            'rwk' => 'Rwa',
            'sa' => 'Sanskrit',
            'sad' => 'Sandawe',
            'saf' => 'Saafi-Saafi',
            'sah' => 'Sakha',
            'sai' => 'South American Indian',
            'sal' => 'Salishan',
            'sam' => 'Samaritan Aramaic',
            'saq' => 'Samburu',
            'sas' => 'Sasak',
            'sat' => 'Santali',
            'sba' => 'Ngambay',
            'sbp' => 'Sangu',
            'sc' => 'Sardinian',
            'scn' => 'Sicilian',
            'sco' => 'Scots',
            'sd' => 'Sindhi',
            'sdc' => 'Sassarese Sardinian',
            'se' => 'Northern Sami',
            'see' => 'Seneca',
            'seh' => 'Sena',
            'sei' => 'Seri',
            'sel' => 'Selkup',
            'sem' => 'Semitic',
            'ses' => 'Koyraboro Senni',
            'sg' => 'Sango',
            'sga' => 'Irish, Old',
            'sgn' => 'Sign Languages',
            'sgs' => 'Samogitian',
            'sh' => 'Serbo-Croatian',
            'shi' => 'Tachelhit',
            'shn' => 'Shan',
            'sho' => 'Shona',
            'shp' => 'Shipibo',
            'shs' => 'Shuswap',
            'si' => 'Sinhala',
            'sid' => 'Sidamo',
            'sio' => 'Siouan',
            'sit' => 'Sino-Tibetan',
            'sk' => 'Slovak',
            'sl' => 'Slovenian',
            'sla' => 'Slavic',
            'sm' => 'Samoan',
            'sma' => 'Southern Sami',
            'smi' => 'Sami',
            'smj' => 'Lule Sami',
            'smn' => 'Inari Sami',
            'sms' => 'Skolt Sami',
            'sn' => 'Shona',
            'snk' => 'Soninke',
            'so' => 'Somali',
            'sog' => 'Sogdien',
            'son' => 'Songhai',
            'sot' => 'Sotho, Southern',
            'spa' => 'Spanish',
            'sq' => 'Albanian',
            'sr' => 'Serbian',
            'srn' => 'Sranan Tongo',
            'srr' => 'Serer',
            'ss' => 'Swati',
            'ssa' => 'Nilo-Saharan',
            'ssy' => 'Saho',
            'st' => 'Sotho, Southern',
            'stq' => 'Saterland Frisian',
            'su' => 'Sundanese',
            'suk' => 'Sukuma',
            'sus' => 'Susu',
            'sux' => 'Sumerian',
            'sv' => 'Swedish',
            'sw' => 'Swahili',
            'swb' => 'Comorian',
            'swc' => 'Congo Swahili',
            'syc' => 'Classical Syriac',
            'syr' => 'Syriac',
            'szl' => 'Silesian',
            'ta' => 'Tamil',
            'tai' => 'Tai',
            'tak' => 'Tak',
            'tal' => 'Tal',
            'tan' => 'Tangale',
            'taq' => 'Tamasheq',
            'tar' => 'Tarahumara',
            'tat' => 'Tatar',
            'tau' => 'Tau',
            'tav' => 'Tavoyan',
            'taw' => 'Tawbuid',
            'tbw' => 'Tagbanwa',
            'tcy' => 'Tulu',
            'te' => 'Telugu',
            'tem' => 'Timne',
            'teo' => 'Teso',
            'ter' => 'Tereno',
            'tet' => 'Tetum',
            'tg' => 'Tajik',
            'th' => 'Thai',
            'ti' => 'Tigrinya',
            'tig' => 'Tigre',
            'tiv' => 'Tiv',
            'tk' => 'Turkmen',
            'tkl' => 'Tokelau',
            'tl' => 'Tagalog',
            'tlh' => 'Klingon',
            'tli' => 'Tlingit',
            'tly' => 'Talysh',
            'tmh' => 'Tamashek',
            'tn' => 'Tswana',
            'to' => 'Tonga',
            'tog' => 'Tonga',
            'toi' => 'Tonga',
            'tok' => 'Toki Pona',
            'ton' => 'Tonga',
            'tpi' => 'Tok Pisin',
            'tr' => 'Turkish',
            'tru' => 'Turoyo',
            'trv' => 'Taroko',
            'ts' => 'Tsonga',
            'tsi' => 'Tsimshian',
            'tt' => 'Tatar',
            'tum' => 'Tumbuka',
            'tup' => 'Tupi',
            'tut' => 'Altaic',
            'tvl' => 'Tuvalu',
            'tw' => 'Twi',
            'twq' => 'Tasawaq',
            'ty' => 'Tahitian',
            'tyv' => 'Tuvinian',
            'tzm' => 'Central Atlas Tamazight',
            'udm' => 'Udmurt',
            'ug' => 'Uighur',
            'uga' => 'Ugaritic',
            'uk' => 'Ukrainian',
            'umb' => 'Umbundu',
            'und' => 'Undetermined',
            'ur' => 'Urdu',
            'uz' => 'Uzbek',
            'vai' => 'Vai',
            've' => 'Venda',
            'vec' => 'Venetian',
            'vep' => 'Veps',
            'vi' => 'Vietnamese',
            'vls' => 'Flemish',
            'vmf' => 'Main-Franconian',
            'vo' => 'Volapük',
            'vot' => 'Votic',
            'vro' => 'Võro',
            'vun' => 'Vunjo',
            'wa' => 'Walloon',
            'wae' => 'Walser',
            'wal' => 'Walamo',
            'war' => 'Waray',
            'was' => 'Washo',
            'wbp' => 'Warlpiri',
            'wo' => 'Wolof',
            'wuu' => 'Wu Chinese',
            'xal' => 'Kalmyk',
            'xh' => 'Xhosa',
            'xmf' => 'Mingrelian',
            'xog' => 'Soga',
            'yao' => 'Yao',
            'yap' => 'Yapese',
            'yav' => 'Yangben',
            'ybb' => 'Yemba',
            'yi' => 'Yiddish',
            'yo' => 'Yoruba',
            'yom' => 'Yombe',
            'yu' => 'Yugoslav',
            'yue' => 'Cantonese',
            'za' => 'Zhuang',
            'zap' => 'Zapotec',
            'zbl' => 'Blissymbols',
            'zea' => 'Zeelandic',
            'zen' => 'Zenaga',
            'zgh' => 'Standard Moroccan Tamazight',
            'zh' => 'Chinese',
            'zu' => 'Zulu',
            'zun' => 'Zuni',
            'zxx' => 'No linguistic content',
            'zza' => 'Zaza'
        ];
    }
    
    /**
     * Get default languages for users
     * Returns array of default languages with their codes and names
     * 
     * @return array
     */
    public static function getDefaultLanguages()
    {
        return [
            ['code' => 'en', 'name' => 'English'],
            ['code' => 'bg', 'name' => 'Bulgarian'],
            ['code' => 'ro', 'name' => 'Romanian'], 
            ['code' => 'ru', 'name' => 'Russian'],
            ['code' => 'tr', 'name' => 'Turkish'],
            ['code' => 'ja', 'name' => 'Japanese'],
            ['code' => 'ko', 'name' => 'Korean'],
            ['code' => 'ar', 'name' => 'Arabic'],
            ['code' => 'fr', 'name' => 'French'],
            ['code' => 'it', 'name' => 'Italian'],
            ['code' => 'de', 'name' => 'German'],
            ['code' => 'pt', 'name' => 'Portuguese']
        ];
    }

    /**
     * Check if a language code exists in world languages
     */
    public static function isValidLanguageCode($code)
    {
        $worldLanguages = self::getWorldLanguages();
        return array_key_exists(strtolower($code), $worldLanguages);
    }

    /**
     * Get language name by code
     */
    public static function getLanguageNameByCode($code)
    {
        $worldLanguages = self::getWorldLanguages();
        return $worldLanguages[strtolower($code)] ?? null;
    }
}
